name: wallet-test
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/wallet-test.yaml
      - wallet/**
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wallet
    steps:
      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare to cache dependencies
        shell: bash
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: pnpm-store-${{ hashFiles('wallet/pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test
